from aiogram.fsm.state import State, StatesGroup, default_state

class FSMStatus(StatesGroup):
    unauthorized_agronomist = State()
    return_from_empty_file = State()
    wait_farmer_id = State()
    selected_farmer = State()
    change_event = State()
    add_event = State()
    delete_event = State()
    enter_status = State()
    change_title = State()
    change_info = State()
    change_end_date = State()
    change_begin_date = State()
    change_notify_about_begin_before_days = State()
    add_type = State()
    add_info = State()
    add_notify = State()
    add_begin_date = State()
    add_end_date = State()
    wait_answer_from_support = State()
    return_from_more_info = State()
    chating = State()
    back_from_add_event = State()