inference_address=http://127.0.0.1:8080
management_address=http://127.0.0.1:8081
metrics_address=http://127.0.0.1:8082
grpc_inference_port=17070
grpc_management_port=17071
enable_grpc_ssl=false
install_py_dep_per_model=false
enable_envvars_config=true
number_of_netty_threads=4
job_queue_size=10
default_workers_per_model=1
disable_token_authorization=true
enable_metrics_api=true
metrics_mode=log
